### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by ZhiQiu-Kinsey** [wszqkzqk/live-photo-conv#8]
FAILED: src/livephototools.dll.p/meson-generated_livemaker.c.obj
"cl" "-Isrc/livephototools.dll.p" "-Isrc" "-I../src" "-I../include" "-ID:/Program Files/msys2/ucrt64/include/glib-2.0" "-ID:/Program Files/msys2/ucrt64/lib/glib-2.0/include" "-ID:/Program Files/msys2/ucrt64/include/gstreamer-1.0" "-ID:/Program Files/msys2/ucrt64/include/gdk-pixbuf-2.0" "-ID:/Program Files/msys2/ucrt64/include/libpng16" "-ID:/Program Files/msys2/ucrt64/include/webp" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/O2" "/Gw" "-DLIBDEFLATE_DLL" "-DINI_SHARED_LIB" "/Fdsrc/livephototools.dll.p/meson-generated_livemaker.c.pdb" /Fosrc/livephototools.dll.p/meson-generated_livemaker.c.obj "/c" src/livephototools.dll.p/livemaker.c
src\livephototools.h(8): fatal error C1083: 无法打开包括文件: “gexiv2/gexiv2.h”: No such file or directory

但是我有安装gexiv2

KinseyPC@Kinsey UCRT64 /h/source/live-photo-conv
$ pkg-config --cflags --libs gexiv2
-ID:/Program\ Files/msys2/ucrt64/include/glib-2.0 -ID:/Program\ Files/msys2/ucrt64/lib/glib-2.0/include -DINI_SHARED_LIB -lgexiv2 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -lssl

**Comment by ZhiQiu-Kinsey** [comment]
大佬能给个编译好的lib吗？

**Comment by wszqkzqk** [comment]
请将全部日志重定向到文件并附上

**Comment by wszqkzqk** [comment]
> 大佬能给个编译好的lib吗？

如果你愿意为此项目贡献一个构建的CI我就可以提供

**Comment by ZhiQiu-Kinsey** [comment]
我换成linux编译成功了，但是我用python去使用的时候报这个错误了
[root@Kinsey src]# python livephoto.py
Traceback (most recent call last):
  File "/mnt/d/ARCH/live-photo-conv/builddir/src/livephoto.py", line 6, in <module>
    livephoto = LivePhotoTools.LivePhotoGst.new("VID_20241126183224861.jpg")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-invoke-error-quark: Could not locate live_photo_conv_live_photo_gst_new: 'live_photo_conv_live_photo_gst_new': python: undefined symbol: live_photo_conv_live_photo_gst_new (1)
[root@Kinsey src]# python livephoto.py
Traceback (most recent call last):
  File "/mnt/d/ARCH/live-photo-conv/builddir/src/livephoto.py", line 6, in <module>
    livephoto = LivePhotoTools.LivePhotoGst.new("VID_20241126183224861.jpg")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-invoke-error-quark: Could not locate live_photo_conv_live_photo_gst_new: 'live_photo_conv_live_photo_gst_new': python: undefined symbol: live_photo_conv_live_photo_gst_new (1)

**Comment by ZhiQiu-Kinsey** [comment]
代码如下
![image](https://github.com/user-attachments/assets/d38226e3-34a8-498d-9977-99873b35aea0)

**Comment by ZhiQiu-Kinsey** [comment]
> 代码如下 ![image](https://private-user-images.githubusercontent.com/22720616/390645865-d38226e3-34a8-498d-9977-99873b35aea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzAyMjMsIm5iZiI6MTczMjc2OTkyMywicGF0aCI6Ii8yMjcyMDYxNi8zOTA2NDU4NjUtZDM4MjI2ZTMtMzRhOC00OThkLTk5NzctOTk4NzNiMzVhZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA0NTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1Zjc0MzZlOGMwYmFmYzUzNTFjMjU1YzczNTlhZDMxNTQ5ZGJiYmVhMWM5MTUxZjg3NGJmMWIwYmY3NTQwOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.e0LhorCue39uw9oofKqP1vYFYR7-8xqedcsdNk2L_lw)
![image](https://github.com/user-attachments/assets/763b084c-e8d1-4976-92ff-c9f51f68d046)

**Comment by wszqkzqk** [comment]
> > 代码如下 ![image](https://private-user-images.githubusercontent.com/22720616/390645865-d38226e3-34a8-498d-9977-99873b35aea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzAyMjMsIm5iZiI6MTczMjc2OTkyMywicGF0aCI6Ii8yMjcyMDYxNi8zOTA2NDU4NjUtZDM4MjI2ZTMtMzRhOC00OThkLTk5NzctOTk4NzNiMzVhZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA0NTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1Zjc0MzZlOGMwYmFmYzUzNTFjMjU1YzczNTlhZDMxNTQ5ZGJiYmVhMWM5MTUxZjg3NGJmMWIwYmY3NTQwOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.e0LhorCue39uw9oofKqP1vYFYR7-8xqedcsdNk2L_lw)
> > ![image](https://private-user-images.githubusercontent.com/22720616/390646595-763b084c-e8d1-4976-92ff-c9f51f68d046.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzA0MTcsIm5iZiI6MTczMjc3MDExNywicGF0aCI6Ii8yMjcyMDYxNi8zOTA2NDY1OTUtNzYzYjA4NGMtZThkMS00OTc2LTkyZmYtYzlmNTFmNjhkMDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA1MDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMDIxMzRmYzJhNzI4MTBhZmU4MGY4NDJjZDI2Mzc3MzM5ZWY1YjQ1N2RmZmZjNDBjMDg1Y2ZkZGY0YzM5MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fkfuPDJgm6Yi8al18GGosPklDaEMyn7436NToaCAGfY)

你怎么安装的

**Comment by ZhiQiu-Kinsey** [comment]
> 代码如下 ![image](https://private-user-images.githubusercontent.com/22720616/390645865-d38226e3-34a8-498d-9977-99873b35aea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzA1NjEsIm5iZiI6MTczMjc3MDI2MSwicGF0aCI6Ii8yMjcyMDYxNi8zOTA2NDU4NjUtZDM4MjI2ZTMtMzRhOC00OThkLTk5NzctOTk4NzNiMzVhZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA1MDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NTdjZDJlN2RlMjQ3YzM1MjA1NTVhNDA0OTMzODgxNmZjOTc2YTBmODJkMjJiZjNiZjFmYmEzNjJiMWI1ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FcPSyEO-OcnghpmmU8lJp4N6NZToB31B4iJnO4ss5w8)

而且当我按照文档直接使用命令行执行报了命令不存在
[root@Kinsey builddir]# live-photo-conv --help
-bash: live-photo-conv: command not found

**Comment by wszqkzqk** [comment]
> > 代码如下 ![image](https://private-user-images.githubusercontent.com/22720616/390645865-d38226e3-34a8-498d-9977-99873b35aea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzA1NjEsIm5iZiI6MTczMjc3MDI2MSwicGF0aCI6Ii8yMjcyMDYxNi8zOTA2NDU4NjUtZDM4MjI2ZTMtMzRhOC00OThkLTk5NzctOTk4NzNiMzVhZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA1MDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NTdjZDJlN2RlMjQ3YzM1MjA1NTVhNDA0OTMzODgxNmZjOTc2YTBmODJkMjJiZjNiZjFmYmEzNjJiMWI1ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FcPSyEO-OcnghpmmU8lJp4N6NZToB31B4iJnO4ss5w8)
> 
> 而且当我按照文档直接使用命令行执行报了命令不存在 [root@Kinsey builddir]# live-photo-conv --help -bash: live-photo-conv: command not found

这不就是你只构建了没有安装吗

**Comment by ZhiQiu-Kinsey** [comment]
> > > 代码如下 ![image](https://private-user-images.githubusercontent.com/22720616/390645865-d38226e3-34a8-498d-9977-99873b35aea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzA1NjEsIm5iZiI6MTczMjc3MDI2MSwicGF0aCI6Ii8yMjcyMDYxNi8zOTA2NDU4NjUtZDM4MjI2ZTMtMzRhOC00OThkLTk5NzctOTk4NzNiMzVhZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA1MDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NTdjZDJlN2RlMjQ3YzM1MjA1NTVhNDA0OTMzODgxNmZjOTc2YTBmODJkMjJiZjNiZjFmYmEzNjJiMWI1ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FcPSyEO-OcnghpmmU8lJp4N6NZToB31B4iJnO4ss5w8)
> > 
> > 
> > 而且当我按照文档直接使用命令行执行报了命令不存在 [root@Kinsey builddir]# live-photo-conv --help -bash: live-photo-conv: command not found
> 
> 这不就是你只构建了没有安装吗

我如何安装？

**Comment by wszqkzqk** [comment]
你用的什么发行版，有没有使用[构建文件](https://github.com/wszqkzqk/live-photo-conv/wiki)

**Comment by ZhiQiu-Kinsey** [comment]
> 你用的什么发行版，有没有使用[构建文件](https://github.com/wszqkzqk/live-photo-conv/wiki)

构建文件如何使用？

**Comment by ZhiQiu-Kinsey** [comment]
> 你用的什么发行版，有没有使用[构建文件](https://github.com/wszqkzqk/live-photo-conv/wiki)

我是按照文档来的，目前应该是编译成功了，出现了LivePhotoTools-0.3.gir和LivePhotoTools-0.3.typelib两个库文件

**Comment by 000lbh** [comment]
> > 代码如下 ![image](https://private-user-images.githubusercontent.com/22720616/390645865-d38226e3-34a8-498d-9977-99873b35aea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzA1NjEsIm5iZiI6MTczMjc3MDI2MSwicGF0aCI6Ii8yMjcyMDYxNi8zOTA2NDU4NjUtZDM4MjI2ZTMtMzRhOC00OThkLTk5NzctOTk4NzNiMzVhZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA1MDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NTdjZDJlN2RlMjQ3YzM1MjA1NTVhNDA0OTMzODgxNmZjOTc2YTBmODJkMjJiZjNiZjFmYmEzNjJiMWI1ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FcPSyEO-OcnghpmmU8lJp4N6NZToB31B4iJnO4ss5w8)
> 
> 而且当我按照文档直接使用命令行执行报了命令不存在 [root@Kinsey builddir]# live-photo-conv --help -bash: live-photo-conv: command not found


Binary is located at `/PATH/TO/PROJECT/builddir/src/` . Please use relative path to execute a binary outside `$PATH` . Remember that binary in current working directory should be executed with prefix `./` .

**Comment by wszqkzqk** [comment]
请先提供你使用的发行版信息

**Comment by wszqkzqk** [comment]
请重新阅读[构建文档](https://github.com/wszqkzqk/live-photo-conv?tab=readme-ov-file#build-scripts)

**Comment by ZhiQiu-Kinsey** [comment]
> 请先提供你使用的发行版信息

5.15.133.1-microsoft-standard-WSL2

**Comment by ZhiQiu-Kinsey** [comment]
> 请重新阅读[构建文档](https://github.com/wszqkzqk/live-photo-conv?tab=readme-ov-file#build-scripts)
当我执行到meson compile -C builddir后提示安装成功了，但是报了另外一个错误

[root@Kinsey src]# live-photo-conv --help
live-photo-conv: error while loading shared libraries: liblivephototools.so: cannot open shared object file: No such file or directory

**Comment by wszqkzqk** [comment]
> > 请先提供你使用的发行版信息
> 
> 5.15.133.1-microsoft-standard-WSL2

不是指内核，指的是发行版，比如Arch Linux, Ubuntu, Debian, openSUSE, Fedora等

**Comment by ZhiQiu-Kinsey** [comment]
> > > 请先提供你使用的发行版信息
> > 
> > 
> > 5.15.133.1-microsoft-standard-WSL2
> 
> 不是指内核，指的是发行版，比如Arch Linux, Ubuntu, Debian, openSUSE, Fedora等

Arch Linux

**Comment by wszqkzqk** [comment]
> > > > 请先提供你使用的发行版信息
> > > 
> > > 
> > > 5.15.133.1-microsoft-standard-WSL2
> > 
> > 
> > 不是指内核，指的是发行版，比如Arch Linux, Ubuntu, Debian, openSUSE, Fedora等
> 
> Arch Linux

请勿`meson install`，直接用AUR安装

**Comment by ZhiQiu-Kinsey** [comment]
> 请重新阅读[构建文档](https://github.com/wszqkzqk/live-photo-conv?tab=readme-ov-file#build-scripts)

我成功运行了，谢谢大佬

**Comment by ZhiQiu-Kinsey** [comment]
重新按照最新文档，成功运行
